version: '3'
services:
  db:
    image: mongo:latest
    container_name: Mongo-container
    restart: always
    # env_file:
    #   - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/bin:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

  job-engine-scraper:
    build: ./jobEngineScraper
    container_name: devjob-scraper-container
    env_file:
      - .env
    volumes: 
      - ./jobEngineScraper:/usr/src/app/scraper
    ports:
      - 5001:6023
    expose:
      - 6023
    depends_on:
      - db
  job-applicator:
    build: ./jobApplicator
    container_name: job-applicator-container
    env_file:
      - .env  
# links is deprecated
